export const LIFE_BAR = {
	DURATION: {
		DAMAGE_BAR_BUMP: 0.04,
		DAMAGE_BAR_SHRINK: 0.32,
		DAMAGE_LIFE_DISPLAY: 0.36,
		DAMAGE_TEXT_SCALE: 0.4,
		DAMAGE_TRAIL: 1.1,
		HEAL_BAR_RISE: 0.38,
		HEAL_BAR_SETTLE: 0.92,
		HEAL_LIFE_DISPLAY: 1.42,
		HEAL_OVERLAY_PULSE: 1.72,
		LOW_LIFE_PULSE: 0.38,
		LOW_LIFE_RECOVER: 0.22,
	},
	ALPHA: {
		DAMAGE_TRAIL: 0.85,
		HEAL_PULSE_PEAK: 0.94,
		HEAL_PULSE_HOLD: 0.68,
		LOW_LIFE_PULSE: 0.35,
	},
	SCALE: {
		DAMAGE_TEXT_PEAK: 1.35,
		HEAL_TEXT_PEAK: 1.28,
	},
	HEAL_PULSE_RISE_END: 0.22,
	HEAL_PULSE_HOLD_END: 0.78,
	HEAL_OVERSHOOT_BASE: 0.05,
	HEAL_OVERSHOOT_GAIN_FACTOR: 0.28,
	DAMAGE_BAR_OVERSHOOT: 0.02,
	LOW_LIFE_THRESHOLD: 5,
} as const;

export const SCREEN_EFFECTS = {
	DURATION: {
		HEAL_PULSE_SCALE: 0.26,
		HEAL_FLASH_RISE: 0.16,
		HEAL_FLASH_DIP: 0.22,
		HEAL_FLASH_FADE: 0.42,
		DAMAGE_SHAKE_PRIMARY: 0.03,
		DAMAGE_SHAKE_SECONDARY: 0.04,
		DAMAGE_SHAKE_TERTIARY: 0.035,
		DAMAGE_SHAKE_SETTLE: 0.1,
		DAMAGE_FLASH_RISE: 0.048,
		DAMAGE_FLASH_DIP: 0.08,
		DAMAGE_FLASH_BURST: 0.04,
		DAMAGE_FLASH_FADE: 0.16,
		HIT_FADE: 1.12,
		HIT_SCALE: 0.28,
		DAMAGE_SCALE_RECOVER: 0.38,
		PROTECTED_SHAKE_PRIMARY: 0.03,
		PROTECTED_SHAKE_SECONDARY: 0.04,
		PROTECTED_SHAKE_SETTLE: 0.1,
		PROTECTED_FLASH_RISE: 0.06,
		PROTECTED_FLASH_FADE: 0.2,
		PROTECTED_SCALE_RECOVER: 0.35,
		SKILL_TINT_IN: 0.12,
		SKILL_TINT_OUT: 0.42,
		SKILL_SCALE_RECOVER: 0.46,
	},
	ALPHA: {
		DAMAGE_FLASH_PEAK: 0.72,
		DAMAGE_FLASH_DIP: 0.1,
		DAMAGE_FLASH_BURST: 0.42,
		PROTECTED_FLASH_PEAK: 0.5,
		HEAL_FLASH_RISE: 0.52,
		HEAL_FLASH_DIP: 0.14,
	},
	SCALE: {
		HEAL_ALTAR_START: 0.992,
		HEAL_ALTAR_PEAK: 1.042,
		DAMAGE_ALTAR_SHRINK: 0.96,
		PROTECTED_ALTAR_SHRINK: 0.97,
		SKILL_PEAK: 1.018,
		HIT_START: 0.2,
	},
	SHAKE: {
		DAMAGE_X_PRIMARY: -12,
		DAMAGE_X_SECONDARY: 10,
		DAMAGE_X_TERTIARY: -5,
		PROTECTED_X_PRIMARY: -8,
		PROTECTED_X_SECONDARY: 6,
	},
	PULSE: {
		RISE_RATIO: 0.32,
		FALL_RATIO: 0.68,
		THRESHOLD: 0.001,
	},
} as const;

export const SKILL_PANEL = {
	DURATION: {
		READY_PULSE: 0.52,
	},
	ALPHA: {
		LOW_LIFE_PULSE: 0.35,
		SKILL_READY_PULSE_MIN: 0.48,
		SKILL_OFF: 0.92,
		SKILL_GLOW_BASE: 0.25,
		SKILL_GLOW_RANGE: 0.16,
	},
} as const;

export const POTION_PANEL = {
	DURATION: {
		PRICE_ANIM: 0.6,
	},
} as const;

export const CREDITS_DISPLAY = {
	DURATION: {
		CREDITS_ANIM: 0.5,
	},
} as const;
