export const BOOT = {
	PROGRESS_FONTS_LOADED: 10,
	PROGRESS_APP_CREATED: 24,
	PROGRESS_ASSETS_START: 32,
	PROGRESS_ASSETS_DONE: 96,
	PROGRESS_ERROR: 18,
	PROGRESS_COMPLETE: 100,
	ASSET_PROGRESS_BASE: 32,
	ASSET_PROGRESS_RANGE: 0.6,
	LOADER_FADEOUT_DELAY_MS: 220,
} as const;

export const DEBUG = {
	DEFAULT_CREDITS: 100,
	MIN_CREDITS: 1,
	MAX_CREDITS: 5000,
} as const;

export const GameConfig = {
	CREDIT_COST: 1.0,
	DEFAULT_DMG: 5,
	INITIAL_POTION_PRICE: 25,
	POTION_HEALTH: 10,
	POTION_PRICE_MULTIPLIER: 2,
} as const satisfies Record<string, number>;
